In [1]:
import random as rd
import numpy as np
import math
print(arr)

NameError: name 'arr' is not defined

# Zadanie 1

Napisz funkcję, która sprawdzi czy w podanej macierzy występuję zadana wartość.

In [3]:
def find_element(array,x):
    return x in array
arr = np.array([range(i,i+3) for i in [1,4,7]])

In [5]:
find_element(arr,5)

True

In [6]:
find_element(arr,10)

False

# Zadanie 2

Napisz funkcję, która zwróci średnią geometryczną wektora liczb (liczby sa dodatnie).

In [7]:
def geometric_mean(g):
    x=np.prod(g)
    x**=1/g.size
    return x
geometric_mean(np.array([1,2,3,4]))

2.2133638394006434

# Zadanie 3

Napisz funkcję, która dla zadanych wektórów obliczy ich iloczyn skalarny.


In [8]:
def scalar_product(x,y):
    if len(x)==len(y):
        return np.dot(x,y)
    else: print("Wektory nie sa rownej dlugosci!")
scalar_product(np.array([1,2,3]), np.array([2,3,4]))

20

# Zadanie 4

Napisz funkcję, która wygeneruje macierz o zadanych rozmiarach z tą sama wartością liczbową ale bez użycia metody np.full().


In [11]:
def create_array(shapes, value):
    array = np.array(shapes[0]*shapes[1]*[value])
    array = array.reshape(shapes)
    return array
create_array((7,8),10)

def full(x,y,n):
    return np.array([[n for i in range(y)]for j in range(x)])
full(2,4,10)


array([[10, 10, 10, 10],
       [10, 10, 10, 10]])

# Zadanie 5

Napisz funkcję, która wygeneruje macierz kwadratową określonego rozmiaru n o zerach na przekątnej i jedynkach na pozostałych pozycjach.


In [13]:
def reverse_eye(size):
    for row in range(0,size):
        for col in range(0,size):
            if(row==col):
                print("0", end=" ")
            else: 
                print("1", end=" ")
        print()
reverse_eye(4)

0 1 1 1 
1 0 1 1 
1 1 0 1 
1 1 1 0 


In [14]:
def fill(n):
    matrix=np.array([[0 for i in range(n)]for j in range(n)])
    np.fill_diagonal(matrix,1)
    return matrix
fill(5)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Zadanie 6

Napisz funkcję, która zamieni wszystkie ujemne wartości w macierzy na 0.


In [12]:
narr = np.array([[-1,2,3],
                [4,-5,6],
                [7,8,-9]])
print(narr.ravel())
print(narr.shape)

def negatives_to_zero(array):
    shapes = array.shape 
    array = array.ravel()
    for i in range(len(array)):
        if array[i] < 0:
            array[i] = 0
    return array.reshape(shapes)

negatives_to_zero(narr)



def positive(m):
    for i,j in np.ndenumerate(m):
        if j<0:
            m[i]=0
    return m        
        
positive(np.array([[1,-3],[-5,9]])) 
    
    
    

[-1  2  3  4 -5  6  7  8 -9]
(3, 3)


array([[1, 0],
       [0, 9]])

# Zadanie 7

Napisz funkcję, która zwróci n największych wartości z zadanej macierzy.


In [19]:
def largest_values(array,n):
    array = array.ravel()
    sorted_index_array = np.argsort(array)
    sorted_array = array[sorted_index_array]
    print("Sorrted array: ", sorted_array)
    result = sorted_array[-n : ]
    print("{} larges value: ".format(n), result)
largest_values(arr,2)

def n_max(m,n):
    m=m.flatten()
    return m[np.argsort(m)[::-1][:n]]
print(n_max(np.array([[1,2,6,7],[10,8,9,3]]),2))




Sorrted array:  [1 2 3 4 5 6 7 8 9]
2 larges value:  [8 9]
[10  9]


# Zadanie 8

Napisz funkcję, która zwróci najczęściej powtarzający się element macierzy.


In [14]:
earr = np.array([[1,2,3],
                 [1,1,1],
                 [3,3,4],
                 [3,3,3]]
               )
def occurs(array):
    array = array.flatten()
    return print("Najczęściej powtarzająca się wartość macierzy: ",np.argmax(np.bincount(array)))

occurs(earr)   

Najczęściej powtarzająca się wartość macierzy:  3


# Zadanie 9 

Napisz funkcję, która dla zadanej macierzy 2d zwróci wiersze z unikalnymi (niepowtarzającymi się) wartośćiami.

In [17]:
def unique(array):
    return np.unique(array)
unique(earr)

array([1, 2, 3, 4])

# Zadanie 10

Napisz funkcję, która obliczy odległość (np. euklidesową) dwóch punktów  P1  i  P2  w  Rn.


In [22]:
def euclidean_distance(a,b):
    return np.linalg.norm(a-b)
print(euclidean_distance(np.array([1,2]),np.array([3,2])))

def euclidean_distance2(a,b):
    return np.sum(np.abs(a-b)**2)**1/2
print(euclidean_distance2(np.array([1,2]),np.array([3,2])))


2.0
2.0


# Zadanie 11
Napisz funkcję, która sprawdzi czy podana macierz X o rozmiarze 2x2 jest rozwiązaniem równania macierzowego  aX^2+bX+c=0 , gdzie  a,b,c  to zadane macierze.

In [20]:
def solve(a,b,c,X):
    eq=a@np.linalg.matrix_power(X,2)+b@X+c
    if np.array_equal(eq,np.zeros((2,2))):
        return "Macierz X jest rozwiązaniem"
    else:
        return "Macierz X nie jest rozwiązaniem"
    
a = np.array([[1,1],[1,1]])
b = np.array([[5,5],[5,5]])
c = np.array([[6,6],[6,6]])
X = np.array([[-1,-1],[-1,-1]])


solve(a,b,c,X)

'Macierz X jest rozwiązaniem'

# Zadanie 12 
Napisz funkcję, która obliczy n-tą liczbę Fibonacciego wykorzystując potęgowanie macierzy [[1,1],[1,0]] (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Macierze_liczb_Fibonacciego).

In [21]:
def Fibonacci(n):
    f = np.array([[1,1],[1,0]])
    f = np.linalg.matrix_power(f,n)
    return str(n)+" liczba Fibonnaciego to "+str(f[0,1])
Fibonacci(6)

'6 liczba Fibonnaciego to 8'

# Zadanie 13
Napisz funkcję, która obliczy n-tą liczbę Fibonacciego wykorzystując wzór Bineta (https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego#Wz%C3%B3r_Bineta).

# Zadanie 14
Napisz funkcję, która wygeneruje macierz o losowych elementach (liczby całkowite z zadanego zakresu) o zadanej z góry wartości śladu macierzy (ang. trace).